In [ ]:
a = [1,2,3,4,5,6,7,8,9,10]
list(filter(lambda x:x%2==0,a))

In [ ]:
def test(A,B,C):
    print(A)
    print(B)
    print(C)

In [ ]:
test(10,20,30,)

In [ ]:
test(x,z,y)

In [ ]:
def adarsh(a,b,c):
    d = a+" "+" "+b+' '+c
    e = d.upper()
    print(e)

In [ ]:
adarsh('Adarsh Kashyap',"I love You", "I like you")

In [ ]:
x = 'I LIKE YOU'
y = 'ADARSH KASHYAP'
z = "I love you"

adarsh(y,x,z)

In [ ]:
def default(a,b,c="Adarsh"):
    c = a+" "+b+" "+c
    print(c)

In [ ]:
default('Hey',"How are you ?")

In [ ]:
a = "Hope you are doing well"
b = "How are you?"


default(b,a)

In [ ]:
def rahul(a,b="Kashyap", c='ji'):

    print(a+' '+b+' '+c)

In [ ]:
rahul("adarsh")

In [ ]:
rahul("I am fine", "You tell","How are you?")

In [ ]:
def ak(a,b,c):
    print(a)
    print(b)
    print(c)

In [ ]:
ak(10,20,c=10)

In [ ]:
def ak(a,b,c=20):
    print(a)
    print(b)
    print(c)

In [ ]:
ak(a,b=90)

In [ ]:
def k(a,b,c):
    print(a)
    print(b)
    print(c)

In [ ]:
k(10,20,c=200)

In [ ]:
k(10,b=60)

In [ ]:
k(100,20)

In [ ]:
k(b=400,c=200,a=600)

In [ ]:
k(20,30,40)

In [ ]:
x = 60
y= 10
z= 65
k(y,z,x)

In [ ]:
def names(*b):
    print(b)

In [ ]:
names("adarsh","kashyap","I love you ")

In [ ]:
names("Kashyap")

In [ ]:
num = (10,20,30)
s=0
for i in num:
    s+=i
    print(i)
    print(s)
print()
print(s)


In [ ]:
for i in range(5):
    print("Adarsh")

In [ ]:
for i in range(5):
    print(i,"adarsh")

In [ ]:
def baad(*c):
    print(c)

In [ ]:
baad('adarsh',"kashyap","Neha", "Chauhan")

In [ ]:
a =[200,30,40]
c=0
for i in a :
    print(i+i)

    

In [ ]:
a =[200,30,40]
c=0
for i in a:
    c+=i
    print(i)
    print(a,[i])
print()
print(c)
    

In [ ]:
def col(a,b,*c):
    print(a)
    print(b)
    print(c)

In [ ]:
col("adarsh","kashyap","Neha","Chauhan","Ji")

In [ ]:
aa= [20,30,40]
ss=0
def add(a,b,c,*d):
    for i in aa:
        ss+=i
print(ss)

In [ ]:
def func(**a):
    print(a)

In [ ]:
func(a=1,b=30,adarsh="Kahsyap",Age=29,Village='Arla')

In [ ]:
def akk(**c):
    print(c)

In [ ]:
akk(a="adarsh",b="Manoj", age=20)

In [ ]:
def akk(**c):
    return akk.keys()

In [ ]:
def adarsh():
    print('I am adarsh')
    return adarsh()

In [ ]:
def password(pas):
    password = 'ADARSH123'
    if pas == password:
        print('Your Password is correct')
    else:
        print('You entered a wrong password')
        pas = input('Enter your password')
        password(pas)

In [ ]:
pas=input(' Enter your password ')
password(pas)

In [7]:
def ada():
    print("Adarsh I Love You")
    ada()

In [6]:
ada()

Adarsh I Love You


In [8]:
dir()

['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'ada',
 'exit',
 'get_ipython',
 'open',
 'quit']

In [15]:
def demo():
    a=10
    b=20
    print(a+b)
    

In [16]:
demo()

30


In [33]:
n = int(input('Enter a number'))

def natural(n):
    print(n)
    if n==2:
        return
    return natural(n-1)
    
natural(n)

Enter a number


ValueError: invalid literal for int() with base 10: ''

In [31]:
natural(9)

9
8
7
6
5
4
3
2


In [47]:
def nat():
    a='hey'
    print(a)
    
    nat()

In [1]:
import numpy as np


In [25]:
np.random.seed(10)
a=np.random.randint(10,200,36).reshape(3,3,4)
a

array([[[ 19, 135,  25,  74],
        [123, 133, 166, 167],
        [123,  18,  83,  10]],

       [[ 50, 174, 125,  26],
        [110, 149,  64,  98],
        [117, 132,  72,  43]],

       [[110, 187, 189,  64],
        [ 87,  23, 163, 136],
        [151, 102,  96,  40]]])

In [103]:
a[0::,-1,-1:-5:-1]

array([[ 10,  83,  18, 123],
       [ 43,  72, 132, 117],
       [ 40,  96, 102, 151]])

In [104]:
a

array([[[ 19, 135,  25,  74],
        [123, 133, 166, 167],
        [123,  18,  83,  10]],

       [[ 50, 174, 125,  26],
        [110, 149,  64,  98],
        [117, 132,  72,  43]],

       [[110, 187, 189,  64],
        [ 87,  23, 163, 136],
        [151, 102,  96,  40]]])

In [115]:
a[0::,[2],[-2]]

array([[83],
       [72],
       [96]])

In [116]:
x=np.array([10,20,30,40,50,60,70,80,90])
np.sum(x)

450

In [118]:
x.sum()

450

In [126]:
a=[20,40,50,60,70]
s=np.array(a)

np.sum(s)

240

In [130]:
np.random.seed(10)
a=np.random.randint(10,100,18).reshape(2,3,3)
a

array([[[19, 25, 74],
        [38, 99, 39],
        [18, 83, 10]],

       [[50, 46, 26],
        [21, 64, 98],
        [72, 43, 82]]])

In [141]:
np.random.seed(10)
v=np.random.randint(10,50,6).reshape(1,6)
v

array([[19, 46, 25, 10, 38, 35]])

In [144]:
np.sum(v,axis=1)

array([173])

In [154]:
np.random.seed(20)
f=np.random.randint(10,50,12).reshape(3,4)
f

array([[45, 36, 25, 41],
       [38, 36, 19, 30],
       [21, 32, 17, 44]])

In [159]:
np.sum(f,axis=0)


array([104, 104,  61, 115])

In [160]:
np.sum(f,axis=1)

array([147, 123, 114])

In [163]:
np.random.seed(10)
j=np.random.randint(1,5,6).reshape(2,3)
j

array([[2, 2, 1],
       [4, 1, 2]])

In [166]:
np.sum(j,axis=1)

array([5, 7])

In [167]:
np.sum(j,axis=0)

array([6, 3, 3])

In [168]:
j

array([[2, 2, 1],
       [4, 1, 2]])

In [169]:
j.max()

4

In [176]:
np.random.seed()
ss=np.random.randint(1,9,32).reshape(2,4,4)
ss

array([[[8, 1, 8, 7],
        [2, 5, 8, 4],
        [8, 3, 7, 8],
        [2, 1, 1, 3]],

       [[5, 3, 5, 8],
        [5, 7, 2, 7],
        [4, 6, 8, 2],
        [7, 3, 6, 7]]])

In [182]:
np.sum(ss,axis=0)

array([[13,  4, 13, 15],
       [ 7, 12, 10, 11],
       [12,  9, 15, 10],
       [ 9,  4,  7, 10]])

In [183]:
np.sum(ss,axis=1)

array([[20, 10, 24, 22],
       [21, 19, 21, 24]])

In [184]:
np.min(ss)

1

In [185]:
np.max(ss)

8

In [187]:
ss.max()

8

In [190]:
s=np.array([10,20,30])
s.mean()

20.0

In [194]:
x=[20,30,40,50,60,70,80,90]
f=20,30,50,80,90,10,20,70
np.mean(x)

55.0

In [200]:
np.sum(x)

440

In [201]:
np.mean(x)

55.0

In [203]:
np.size(x)

8

In [204]:
440/8

55.0

In [210]:
np.random.seed(10)
aa=np.random.randint(10,50,4).reshape(2,2)
aa

array([[19, 46],
       [25, 10]])

In [212]:
aa.mean()

25.0

In [213]:
np.size(aa)

4

In [216]:
aa.sum()/np.size(aa)

25.0

In [215]:
100/4

25.0

In [219]:
np.random.seed()
dd=np.random.randint(10,20,9).reshape(3,3)
dd

array([[15, 18, 15],
       [12, 14, 17],
       [17, 12, 13]])

In [221]:
np.mean(dd,axis=1)

array([16.        , 14.33333333, 14.        ])

In [1]:
import numpy as np

In [5]:
np.random.seed(100)
k=np.random.randint(10,100,24).reshape(2,4,3)
k

array([[[18, 34, 77],
        [97, 89, 58],
        [20, 62, 63],
        [76, 24, 44]],

       [[34, 25, 70],
        [68, 26, 19],
        [96, 12, 37],
        [14, 41, 11]]])

In [6]:
np.median(k)

39.0

In [7]:
np.median(k,axis=0)

array([[26. , 29.5, 73.5],
       [82.5, 57.5, 38.5],
       [58. , 37. , 50. ],
       [45. , 32.5, 27.5]])

In [9]:
np.median(k,axis=1)

array([[48. , 48. , 60.5],
       [51. , 25.5, 28. ]])

In [10]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [11]:
k

array([[[18, 34, 77],
        [97, 89, 58],
        [20, 62, 63],
        [76, 24, 44]],

       [[34, 25, 70],
        [68, 26, 19],
        [96, 12, 37],
        [14, 41, 11]]])

In [12]:
np.std(k)

27.2885494402974

In [13]:
np.std(k,axis=0)

array([[ 8. ,  4.5,  3.5],
       [14.5, 31.5, 19.5],
       [38. , 25. , 13. ],
       [31. ,  8.5, 16.5]])

In [14]:
np.std(k,axis=1)

array([[34.56425176, 25.38084908, 11.80042372],
       [31.44837039, 10.27131929, 22.68672519]])

In [15]:
k

array([[[18, 34, 77],
        [97, 89, 58],
        [20, 62, 63],
        [76, 24, 44]],

       [[34, 25, 70],
        [68, 26, 19],
        [96, 12, 37],
        [14, 41, 11]]])

In [16]:
k.var()

744.6649305555555

In [17]:
np.var(k)

744.6649305555555

In [18]:
np.var(k,axis=0)


array([[  64.  ,   20.25,   12.25],
       [ 210.25,  992.25,  380.25],
       [1444.  ,  625.  ,  169.  ],
       [ 961.  ,   72.25,  272.25]])

In [19]:
np.var(k,axis=1)

array([[1194.6875,  644.1875,  139.25  ],
       [ 989.    ,  105.5   ,  514.6875]])

In [27]:
np.random.seed(10)
n=np.random.randint(1,10,5).reshape(1,5)
n

array([[5, 1, 2, 1, 2]])

In [34]:
np.argmin(n), np.max(n)

(1, 5)

In [36]:
np.argmin(n),np.min(n)

(1, 1)

In [39]:
np.max(n),np.argmax(n)

(5, 0)

In [42]:
np.random.seed(10)
n=np.random.randint(1,10,10).reshape(2,5)
n

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5]])

In [44]:
np.min(n,axis=0)

array([5, 1, 2, 1, 2])

In [46]:
np.max(n,axis=1)

array([5, 9])

In [52]:
n

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5]])

In [53]:
np.argmax(n,axis=0),np.max(n,axis=0)

(array([1, 0, 1, 1, 1], dtype=int64), array([9, 1, 9, 7, 5]))

In [78]:
np.random.seed(1)
d=np.random.randint(100,200,8).reshape(2,2,2)
d

array([[[137, 112],
        [172, 109]],

       [[175, 105],
        [179, 164]]])

In [79]:
d.min()

105

In [80]:
d.max()

179

In [81]:
d

array([[[137, 112],
        [172, 109]],

       [[175, 105],
        [179, 164]]])

In [82]:
d.argmax()

6

In [83]:
d

array([[[137, 112],
        [172, 109]],

       [[175, 105],
        [179, 164]]])

In [84]:
np.argmax(d,axis=0)

array([[1, 0],
       [1, 1]], dtype=int64)

In [77]:
np.max(d,axis=0)

array([[175, 112],
       [179, 171]])

In [89]:
np.array([10,20,30])

array([10, 20, 30])

In [92]:
a=[10,10,9,9]
s=np.array(a)
s

array([10, 10,  9,  9])

In [95]:
np.sqrt(s)

array([3.16227766, 3.16227766, 3.        , 3.        ])

In [96]:
d

array([[[137, 112],
        [172, 109]],

       [[175, 105],
        [179, 164]]])

In [99]:
np.argwhere(d)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]], dtype=int64)

In [100]:
d

array([[[137, 112],
        [172, 109]],

       [[175, 105],
        [179, 164]]])

In [102]:
np.where(d>100)

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 1, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [122]:
np.random.seed()
t=np.random.randint(10,20,16).reshape(4,4)
t

array([[14, 17, 17, 19],
       [16, 19, 14, 14],
       [15, 10, 12, 19],
       [12, 15, 15, 15]])

In [125]:
np.where(t>15)

(array([0, 0, 0, 1, 1, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 3], dtype=int64))

In [127]:
t[np.where(t>10)]=0
t

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0, 10,  0,  0],
       [ 0,  0,  0,  0]])

In [158]:
np.random.seed(1)
d=np.random.randint(100,200,8).reshape(2,2,2)
d

array([[[137, 112],
        [172, 109]],

       [[175, 105],
        [179, 164]]])

In [162]:
np.where(d>120,'True',d)

array([[['True', '112'],
        ['True', '109']],

       [['True', '105'],
        ['True', 'True']]], dtype='<U11')

In [1]:
import numpy as np

In [14]:
np.random.seed(10)
x=np.random.randint(100,200,9).reshape(3,3)
x

array([[109, 115, 164],
       [128, 189, 193],
       [129, 108, 173]])

In [15]:
np.clip(x,120,150)

array([[120, 120, 150],
       [128, 150, 150],
       [129, 120, 150]])

In [22]:
x=np.array(['Married','Unmarried','Single','Married','Divorced','Widowed','Single','Unmarried',
          'Divorced','Widowed','Unmarried','Unmarried',]).reshape(4,3)

In [23]:
x

array([['Married', 'Unmarried', 'Single'],
       ['Married', 'Divorced', 'Widowed'],
       ['Single', 'Unmarried', 'Divorced'],
       ['Widowed', 'Unmarried', 'Unmarried']], dtype='<U9')

In [29]:
con_lst=[x=='Married',x=='Single',x=='Widowed',x=='Unmarried']
cho_list=['Unmarried','Going to marry someone new','Not Intetrested in marrige','Single']

In [30]:
np.select(con_lst,cho_list)

array([['Unmarried', 'Single', 'Going to marry someone new'],
       ['Unmarried', '0', 'Not Intetrested in marrige'],
       ['Going to marry someone new', 'Single', '0'],
       ['Not Intetrested in marrige', 'Single', 'Single']], dtype='<U26')

In [37]:
x=['Neha','Adarsh','Kashyap','Manoj','Gurgaon','Agra']
s=np.array(x)


In [46]:
con= [s=='Neha',s=='Adarsh',s=='Gurgaon',s=='Agra',]
choice_lst=['Nehaa','Aadarsh','Gurgram','Tajmhal']

In [47]:
np.select(con,choice_lst)

array(['Nehaa', 'Aadarsh', '0', '0', 'Gurgram', 'Tajmhal'], dtype='<U7')

In [54]:
x=[10,20,30,40,np.nan,np.nan,60,]
s=np.array(x)

In [56]:
s[np.isnan(s)]

array([nan, nan])

In [ ]:
s[np.isnan]

In [61]:

np.isnan(s).sum()

2

In [64]:
x=[10,20,30,40,np.nan,np.nan,60,np.nan,80,np.nan]
r=np.array(x)
r

array([10., 20., 30., 40., nan, nan, 60., nan, 80., nan])

In [65]:
np.isnan(r)

array([False, False, False, False,  True,  True, False,  True, False,
        True])

In [70]:
np.isnan(r).sum().sum()

4

In [74]:
lst=[10,30,40,50,60,np.nan,np.nan,np.nan,70]
e=np.array(lst)

In [148]:
e.ndim

1

In [77]:
np.isnan(e)

array([False, False, False, False, False,  True,  True,  True, False])

In [79]:
e[np.isnan(e)].sum()

nan

In [80]:
np.isnan(e).sum()

3

In [84]:
[np.where(np.isnan(e))]

[(array([5, 6, 7], dtype=int64),)]

In [82]:
e

array([10., 30., 40., 50., 60., nan, nan, nan, 70.])

In [89]:
lst=[10,30,40,50,60,70,np.nan,np.nan,np.nan]
s=np.array(lst)
s

array([10., 30., 40., 50., 60., 70., nan, nan, nan])

In [87]:
np.isnan(s)

array([False, False, False, False, False, False])

In [90]:
np.isnan(s)

array([False, False, False, False, False, False,  True,  True,  True])

In [94]:
s[np.isnan(s).sum()]

50.0

In [98]:
[np.where(np.isnan(s))]

[(array([6, 7, 8], dtype=int64),)]

In [102]:
(np.isnan(s)==False).sum()

6

In [103]:
s.size

9

In [104]:
s

array([10., 30., 40., 50., 60., 70., nan, nan, nan])

In [105]:
# Total size- null values= not nulll values

In [109]:
s.size-np.isnan(s).sum()

6

In [110]:
s

array([10., 30., 40., 50., 60., 70., nan, nan, nan])

In [117]:
np.where(np.isnan(s))

(array([6, 7, 8], dtype=int64),)

In [120]:
s[np.isnan(s)]=0

In [121]:
s

array([10., 30., 40., 50., 60., 70.,  0.,  0.,  0.])

In [124]:
np.isnan(s)==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [125]:
s

array([10., 30., 40., 50., 60., 70.,  0.,  0.,  0.])

In [179]:
s=[[10,20,30,40,np.nan,np.nan,]]

In [180]:
ss=np.array(s)
ss

array([[10., 20., 30., 40., nan, nan]])

In [181]:
ss.ndim

2

In [182]:
np.isnan(ss)

array([[False, False, False, False,  True,  True]])

In [189]:
np.where(np.isnan(ss))

(array([0, 0], dtype=int64), array([4, 5], dtype=int64))

In [194]:
ss[(np.where(np.isnan(ss)))]=0

In [195]:
ss

array([[0., 0., 0., 0., 0., 0.]])

In [201]:
np.random.seed(10)
s=np.random.randint(10,100,10).reshape(2,5)

In [202]:
s

array([[19, 25, 74, 38, 99],
       [39, 18, 83, 10, 50]])

In [204]:
s[s>40]

array([74, 99, 83, 50])

In [205]:
s>40

array([[False, False,  True, False,  True],
       [False, False,  True, False,  True]])

In [211]:
s[s>40]

array([74, 99, 83, 50])

In [230]:
s[(s>40)|( s<30)]

array([19, 25, 74, 99, 18, 83, 10, 50])

In [233]:
s[s%2==0]&[s%3==0]

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)

In [235]:
s[(s%2==0 ) & (s%3==0)]

array([18])

In [238]:
s[~((s%2!=0) &(s%3!=0))]

array([74, 38, 99, 39, 18, 10, 50])

In [239]:
np.random.seed(10)
s=np.random.randint(10,100,10).reshape(2,5)

In [240]:
s

array([[19, 25, 74, 38, 99],
       [39, 18, 83, 10, 50]])

In [242]:
np.concatenate((s))

array([19, 25, 74, 38, 99, 39, 18, 83, 10, 50])

In [252]:
x=np.array([10,20,30,40,50,30]).reshape(2,3)

In [253]:
y=np.array([30,40,60,80]).reshape(2,2)

(array([[30, 40],
        [60, 80]]),
 array([[10, 20, 30],
        [40, 50, 30]]))

In [258]:
np.concatenate((x,y),axis=1)

array([[10, 20, 30, 30, 40],
       [40, 50, 30, 60, 80]])

In [265]:
x,  y,

(array([[10, 20, 30],
        [40, 50, 30]]),
 array([[30, 40],
        [60, 80]]))

In [266]:
np.concatenate((y,x),axis=1)

array([[30, 40, 10, 20, 30],
       [60, 80, 40, 50, 30]])

In [279]:
np.random.seed(10)
d=np.random.randint(10,50,12).reshape(3,4)

In [280]:
np.random.seed(10)
e=np.random.randint(10,50,15).reshape(3,5)

In [281]:
e

array([[19, 46, 25, 10, 38],
       [35, 39, 39, 18, 19],
       [10, 46, 26, 46, 21]])

In [282]:
d

array([[19, 46, 25, 10],
       [38, 35, 39, 39],
       [18, 19, 10, 46]])

In [283]:
np.concatenate((e,d),axis=1)

array([[19, 46, 25, 10, 38, 19, 46, 25, 10],
       [35, 39, 39, 18, 19, 38, 35, 39, 39],
       [10, 46, 26, 46, 21, 18, 19, 10, 46]])

In [284]:
np.array(arange(10,20))

NameError: name 'arange' is not defined

In [288]:
s=np.arange(10,20,2)

In [289]:
s

array([10, 12, 14, 16, 18])

In [290]:
for i in s :
    print(i)

10
12
14
16
18


In [291]:
x=np.array([10,20,30,40,50,60,70,80,90,100,110,120])
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [297]:
for i in x:
    
    for j in x:
        
        print(i)

10
10
10
10
10
10
10
10
10
10
10
10
20
20
20
20
20
20
20
20
20
20
20
20
30
30
30
30
30
30
30
30
30
30
30
30
40
40
40
40
40
40
40
40
40
40
40
40
50
50
50
50
50
50
50
50
50
50
50
50
60
60
60
60
60
60
60
60
60
60
60
60
70
70
70
70
70
70
70
70
70
70
70
70
80
80
80
80
80
80
80
80
80
80
80
80
90
90
90
90
90
90
90
90
90
90
90
90
100
100
100
100
100
100
100
100
100
100
100
100
110
110
110
110
110
110
110
110
110
110
110
110
120
120
120
120
120
120
120
120
120
120
120
120


In [300]:
x=np.array([10,20,30,40,50,60,70,80,90,100,110,120]).reshape(4,3)
x.size

12

In [303]:
x.ndim

2

In [302]:
for i in x:
    print(i)

[10 20 30]
[40 50 60]
[70 80 90]
[100 110 120]


In [304]:
x=np.array([10,20,30,40,50,60,70,80,90,100,110,120]).reshape(2,4,3)


ValueError: cannot reshape array of size 12 into shape (2,4,3)

In [305]:
x=np.random.randint(10,100,36).reshape(3,4,3)

In [306]:
x

array([[[64, 98, 72],
        [43, 82, 88],
        [59, 61, 64],
        [87, 79, 23]],

       [[35, 23, 96],
        [40, 40, 99],
        [22, 75, 41],
        [67, 46, 37]],

       [[28, 87, 32],
        [33, 21, 38],
        [84, 98, 19],
        [25, 28, 90]]])

In [312]:
for i in x:
    print(i)
    print('\n')

[[64 98 72]
 [43 82 88]
 [59 61 64]
 [87 79 23]]


[[35 23 96]
 [40 40 99]
 [22 75 41]
 [67 46 37]]


[[28 87 32]
 [33 21 38]
 [84 98 19]
 [25 28 90]]




In [313]:
x

array([[[64, 98, 72],
        [43, 82, 88],
        [59, 61, 64],
        [87, 79, 23]],

       [[35, 23, 96],
        [40, 40, 99],
        [22, 75, 41],
        [67, 46, 37]],

       [[28, 87, 32],
        [33, 21, 38],
        [84, 98, 19],
        [25, 28, 90]]])

In [317]:
x[0]

array([[64, 98, 72],
       [43, 82, 88],
       [59, 61, 64],
       [87, 79, 23]])

In [318]:
x[0].T

array([[64, 43, 59, 87],
       [98, 82, 61, 79],
       [72, 88, 64, 23]])

In [319]:
x=np.array([10,20,30,40,50,60]).reshape(2,3)
x

array([[10, 20, 30],
       [40, 50, 60]])

In [320]:
y=np.array([2,4]).reshape(2,1)
y

array([[2],
       [4]])

In [321]:
x*y

array([[ 20,  40,  60],
       [160, 200, 240]])

In [325]:
x/y

array([[ 5. , 10. , 15. ],
       [10. , 12.5, 15. ]])

In [330]:
import pandas as pd

In [332]:
y

array([[2],
       [4]])

In [334]:
lst=[10,20,30,40,50]
num=pd.Series(lst)

In [335]:
num

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [338]:
lst=['Neha','Adarsh','Kashyap','Janki','Shri Ram','Hanuman Ji','Jamvant Ji']
num=pd.Series(lst)

In [343]:
num

0          Neha
1        Adarsh
2       Kashyap
3         Janki
4      Shri Ram
5    Hanuman Ji
6    Jamvant Ji
dtype: object

In [355]:
num.index

Index(['A', 's', 'h', 's', 's', 's', 'h'], dtype='object')

In [344]:
num.shape

(7,)

In [346]:
num.index

RangeIndex(start=0, stop=7, step=1)

In [352]:
num.index=list('Ashsssh')

In [353]:
num

A          Neha
s        Adarsh
h       Kashyap
s         Janki
s      Shri Ram
s    Hanuman Ji
h    Jamvant Ji
dtype: object

In [354]:
num.index

Index(['A', 's', 'h', 's', 's', 's', 'h'], dtype='object')

In [361]:
num.index=['Emoloyee' + str(i+1)for i in range(len(num))]

In [366]:
num

Emoloyee1          Neha
Emoloyee2        Adarsh
Emoloyee3       Kashyap
Emoloyee4         Janki
Emoloyee5      Shri Ram
Emoloyee6    Hanuman Ji
Emoloyee7    Jamvant Ji
dtype: object

In [369]:
print(num.values)

['Neha' 'Adarsh' 'Kashyap' 'Janki' 'Shri Ram' 'Hanuman Ji' 'Jamvant Ji']


In [2]:
import pandas as pd

In [10]:
lst=(10,20,30,40,50,60)
pd.Series(lst)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [11]:
lst.index

<function tuple.index(value, start=0, stop=9223372036854775807, /)>

In [12]:
lst

(10, 20, 30, 40, 50, 60)

In [15]:
lst.index=list('abcdef')

AttributeError: 'tuple' object attribute 'index' is read-only

In [18]:
lst= pd.Series([10,20,30,4,0,50])

In [25]:
(dtype,lst.shape)

NameError: name 'dtype' is not defined

In [26]:
len(lst)

6

In [27]:
lst

0    10
1    20
2    30
3     4
4     0
5    50
dtype: int64

In [30]:
lst.index

RangeIndex(start=0, stop=6, step=1)

In [31]:
lst.index=list('ABCDEF')

In [32]:
lst

A    10
B    20
C    30
D     4
E     0
F    50
dtype: int64

In [34]:
lst.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [35]:
lst.values

array([10, 20, 30,  4,  0, 50], dtype=int64)

In [36]:
lst.index=['emp_'+str(i+1) for i in range(len(lst))]

In [37]:
lst

emp_1    10
emp_2    20
emp_3    30
emp_4     4
emp_5     0
emp_6    50
dtype: int64

In [40]:
lst.name='Adarsh'

In [41]:
lst

emp_1    10
emp_2    20
emp_3    30
emp_4     4
emp_5     0
emp_6    50
Name: Adarsh, dtype: int64

In [42]:
lst.name='Practise '

In [43]:
lst

emp_1    10
emp_2    20
emp_3    30
emp_4     4
emp_5     0
emp_6    50
Name: Practise , dtype: int64

In [44]:
emp_names=pd.Series(['Divya','Nikhil','Akansha','Gopal','Sunil','Saif Ali','Gyan','Vamsi','Ritesh','Sarwar','Mayank','Rudra','Shiva','Bandi'])


In [45]:
emp_names

0        Divya
1       Nikhil
2      Akansha
3        Gopal
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [46]:
emp_names.name='Kashyap'

In [50]:
emp_names.size

14

In [54]:
emp_names.dtype

dtype('O')

In [55]:
lst=[20,30,40,50,60,]
s=pd.Series(lst)

In [57]:
s

0    20
1    30
2    40
3    50
4    60
dtype: int64

In [60]:
s[2]

40

In [62]:
s.index=list('abcde')

In [63]:
s

a    20
b    30
c    40
d    50
e    60
dtype: int64

In [68]:
s['a'],s['b'],s['e']

(20, 30, 60)

In [78]:
print(s.iloc['a'])

TypeError: Cannot index by location index with a non-integer key

In [77]:
print(s.loc['a'])

20


In [76]:
s

a    20
b    30
c    40
d    50
e    60
dtype: int64

In [79]:
lst=[20,30,40,50,60,70,80]
p=pd.Series(lst)

In [80]:
p

0    20
1    30
2    40
3    50
4    60
5    70
6    80
dtype: int64

In [81]:
p.iloc[0]

20

In [82]:
p.iloc[1]

30

In [83]:
p.index=list('ABCDEFG')

In [84]:
p

A    20
B    30
C    40
D    50
E    60
F    70
G    80
dtype: int64

In [85]:
p.name='ADARSH'

In [86]:
p

A    20
B    30
C    40
D    50
E    60
F    70
G    80
Name: ADARSH, dtype: int64

In [88]:
p.loc['A']

20

In [89]:
p.loc['B']

30

In [90]:
p.loc['C']

40

In [91]:
p.loc[::]

A    20
B    30
C    40
D    50
E    60
F    70
G    80
Name: ADARSH, dtype: int64

In [93]:
p.loc['A':'E']

A    20
B    30
C    40
D    50
E    60
Name: ADARSH, dtype: int64

In [95]:
p.loc["D":'E']

D    50
E    60
Name: ADARSH, dtype: int64

In [96]:
p.loc[::-1]

G    80
F    70
E    60
D    50
C    40
B    30
A    20
Name: ADARSH, dtype: int64

In [97]:
p.loc['G']='Kashyp'

In [98]:
p

A        20
B        30
C        40
D        50
E        60
F        70
G    Kashyp
Name: ADARSH, dtype: object

In [100]:
p.loc[('D')]='Adarsh'

In [101]:
p

A        20
B        30
C        40
D    Adarsh
E        60
F        70
G    Kashyp
Name: ADARSH, dtype: object

In [103]:
p[p=='Adarsh']='Rahul'

In [104]:
p

A        20
B        30
C        40
D     Rahul
E        60
F        70
G    Kashyp
Name: ADARSH, dtype: object

In [106]:
p[p=='Kashyp']='Sharma'

In [107]:
p

A        20
B        30
C        40
D     Rahul
E        60
F        70
G    Sharma
Name: ADARSH, dtype: object

In [108]:
emp={'Name':'Mohit','Age':28,'City':'Pune','Company':'Infosys','Phone':'1234567890'}
emp

{'Name': 'Mohit',
 'Age': 28,
 'City': 'Pune',
 'Company': 'Infosys',
 'Phone': '1234567890'}

In [110]:
s=pd.Series(emp)

In [111]:
s

Name            Mohit
Age                28
City             Pune
Company       Infosys
Phone      1234567890
dtype: object

In [112]:
s.iloc[0]

'Mohit'

In [115]:
s.iloc[2]

'Pune'

In [116]:
s.loc['Name']

'Mohit'

In [117]:
s.iloc[::-1]

Phone      1234567890
Company       Infosys
City             Pune
Age                28
Name            Mohit
dtype: object

In [120]:
s[s=='Pune']='Chandigarh'

In [121]:
s

Name            Mohit
Age                28
City       Chandigarh
Company       Infosys
Phone      1234567890
dtype: object

In [126]:
s.loc['Name']='Adarsh'

In [127]:
s

Name           Adarsh
Age                28
City       Chandigarh
Company       Infosys
Phone      1234567890
dtype: object

In [1]:
import pandas as pd

In [2]:
names=['Akansha','Gopal','Suresh','Divya','Nikhil']
codes=[101,102,103,104,105]
city=['Pune','Chennai','Madurai','Dehradun','Delhi']

In [7]:
pd.DataFrame((names,codes,city))

0        1        2         3       4
0  Akansha    Gopal   Suresh     Divya  Nikhil
1      101      102      103       104     105
2     Pune  Chennai  Madurai  Dehradun   Delhi

In [4]:
names=['Akansha','Gopal','Suresh','Divya','Nikhil']
codes=[101,102,103,104,105]
city=['Pune','Chennai','Madurai','Dehradun','Delhi']

In [5]:
lst=[names,codes,city]

In [6]:
pd.DataFrame(lst)

0        1        2         3       4
0  Akansha    Gopal   Suresh     Divya  Nikhil
1      101      102      103       104     105
2     Pune  Chennai  Madurai  Dehradun   Delhi

In [8]:
names=['Akansha','Gopal','Suresh','Divya','Nikhil']
codes=[101,102,103,104,105]
city=['Pune','Chennai','Madurai','Dehradun','Delhi']

In [11]:
s=pd.DataFrame((names,codes,city))

In [12]:
s

0        1        2         3       4
0  Akansha    Gopal   Suresh     Divya  Nikhil
1      101      102      103       104     105
2     Pune  Chennai  Madurai  Dehradun   Delhi

In [24]:
ass=s.T

In [25]:
ass

0    1         2
0  Akansha  101      Pune
1    Gopal  102   Chennai
2   Suresh  103   Madurai
3    Divya  104  Dehradun
4   Nikhil  105     Delhi

In [33]:
ass.columns=['Name','Name ID','City']

In [34]:
ss

Name Name ID      City
0  Akansha     101      Pune
1    Gopal     102   Chennai
2   Suresh     103   Madurai
3    Divya     104  Dehradun
4   Nikhil     105     Delhi

In [36]:
ss.index=['emp_'+str(i+1) for i in range(len(ss))]

In [37]:
ss

Name Name ID      City
emp_1  Akansha     101      Pune
emp_2    Gopal     102   Chennai
emp_3   Suresh     103   Madurai
emp_4    Divya     104  Dehradun
emp_5   Nikhil     105     Delhi

In [44]:
ss.name='Name'

In [45]:
ss

Name Name ID      City
emp_1  Akansha     101      Pune
emp_2    Gopal     102   Chennai
emp_3   Suresh     103   Madurai
emp_4    Divya     104  Dehradun
emp_5   Nikhil     105     Delhi

In [43]:
ss

Name Name ID      City
emp_1  Akansha     101      Pune
emp_2    Gopal     102   Chennai
emp_3   Suresh     103   Madurai
emp_4    Divya     104  Dehradun
emp_5   Nikhil     105     Delhi

In [74]:
code.name="ID"

NameError: name 'code' is not defined

In [50]:
ss

Name Name ID      City
emp_1  Akansha     101      Pune
emp_2    Gopal     102   Chennai
emp_3   Suresh     103   Madurai
emp_4    Divya     104  Dehradun
emp_5   Nikhil     105     Delhi

In [59]:
lst=[['Akansha',101,'Pune'],['Gopal',102,'Chennai'],['Suresh',103,'Madurai'],['Divya',104,'Dehradun'],['Nikhil',105,'Delhi']]
lst

[['Akansha', 101, 'Pune'],
 ['Gopal', 102, 'Chennai'],
 ['Suresh', 103, 'Madurai'],
 ['Divya', 104, 'Dehradun'],
 ['Nikhil', 105, 'Delhi']]

In [62]:
x=pd.DataFrame((lst))

In [63]:
x

0    1         2
0  Akansha  101      Pune
1    Gopal  102   Chennai
2   Suresh  103   Madurai
3    Divya  104  Dehradun
4   Nikhil  105     Delhi

In [64]:
x.columns=['Name','ID','City']

In [65]:
x

Name   ID      City
0  Akansha  101      Pune
1    Gopal  102   Chennai
2   Suresh  103   Madurai
3    Divya  104  Dehradun
4   Nikhil  105     Delhi

In [66]:
lst

[['Akansha', 101, 'Pune'],
 ['Gopal', 102, 'Chennai'],
 ['Suresh', 103, 'Madurai'],
 ['Divya', 104, 'Dehradun'],
 ['Nikhil', 105, 'Delhi']]

In [67]:
s=pd.Series(lst)

In [68]:
s

0      [Akansha, 101, Pune]
1     [Gopal, 102, Chennai]
2    [Suresh, 103, Madurai]
3    [Divya, 104, Dehradun]
4      [Nikhil, 105, Delhi]
dtype: object

In [69]:
lst

[['Akansha', 101, 'Pune'],
 ['Gopal', 102, 'Chennai'],
 ['Suresh', 103, 'Madurai'],
 ['Divya', 104, 'Dehradun'],
 ['Nikhil', 105, 'Delhi']]

In [70]:
name_ser=pd.Series(lst)

In [71]:
name_ser

0      [Akansha, 101, Pune]
1     [Gopal, 102, Chennai]
2    [Suresh, 103, Madurai]
3    [Divya, 104, Dehradun]
4      [Nikhil, 105, Delhi]
dtype: object

In [72]:
codes

[101, 102, 103, 104, 105]

In [ ]:
names=['Akansha','Gopal','Suresh','Divya','Nikhil']
codes=[101,102,103,104,105]
city=['Pune','Chennai','Madurai','Dehradun','Delhi']

In [75]:
names

['Akansha', 'Gopal', 'Suresh', 'Divya', 'Nikhil']

In [79]:
names_ser=pd.Series(names)

In [81]:
code_ser=pd.Series(codes)

In [83]:
city_ser=pd.Series(city)

In [84]:
city_ser

0        Pune
1     Chennai
2     Madurai
3    Dehradun
4       Delhi
dtype: object

In [87]:
d=pd.DataFrame((names_ser,code_ser,city_ser)).T

In [88]:
d

0    1         2
0  Akansha  101      Pune
1    Gopal  102   Chennai
2   Suresh  103   Madurai
3    Divya  104  Dehradun
4   Nikhil  105     Delhi

In [91]:
adarsh=['Adarsh',100, 'Kashyap','Rahul','Manoj']
e=pd.Series(adarsh)

In [92]:
e

0     Adarsh
1        100
2    Kashyap
3      Rahul
4      Manoj
dtype: object

In [93]:
adarsh=['Adarsh',100, 'Kashyap','Rahul','Manoj']
ID=[100,200,300,400,500,]
phone=[8219902873,8219902873,8219902873,8219902873,8219902873]

In [94]:
s=pd.DataFrame((adarsh,ID,phone))

In [95]:
s

0           1           2           3           4
0      Adarsh         100     Kashyap       Rahul       Manoj
1         100         200         300         400         500
2  8219902873  8219902873  8219902873  8219902873  8219902873

In [96]:
s.T

0    1           2
0   Adarsh  100  8219902873
1      100  200  8219902873
2  Kashyap  300  8219902873
3    Rahul  400  8219902873
4    Manoj  500  8219902873

In [97]:
s

0           1           2           3           4
0      Adarsh         100     Kashyap       Rahul       Manoj
1         100         200         300         400         500
2  8219902873  8219902873  8219902873  8219902873  8219902873

In [99]:
d=s.T

In [103]:
d.columns=['Name','ID','Contact']

In [106]:
d.index=

TypeError: Index(...) must be called with a collection of some kind, 'ADAAA' was passed

In [110]:
dic={'Name':'Adarsh','Age':20, 'City':'Pune'}

In [113]:
pd.DataFrame(dic)

ValueError: If using all scalar values, you must pass an index

In [116]:
dic={'Name':['Adarsh','Neha','Shikha'],
    'Emp_ID':[101,102,103],
    'City':['Pune','Chandigarh','Delhi']}

In [117]:
dic

{'Name': ['Adarsh', 'Neha', 'Shikha'],
 'Emp_ID': [101, 102, 103],
 'City': ['Pune', 'Chandigarh', 'Delhi']}

In [119]:
s=pd.DataFrame(dic)

In [120]:
s

Name  Emp_ID        City
0  Adarsh     101        Pune
1    Neha     102  Chandigarh
2  Shikha     103       Delhi

In [138]:
s

NAME   ID        CITY
0  Adarsh  101        Pune
1    Neha  102  Chandigarh
2  Shikha  103       Delhi

In [139]:
d=pd.DataFrame(s,columns=['Name','ID','CITY','Department','Compaany'])

In [137]:
d

Name   ID        CITY  Department  Compaany
0   NaN  101        Pune         NaN       NaN
1   NaN  102  Chandigarh         NaN       NaN
2   NaN  103       Delhi         NaN       NaN

In [140]:
lst=[['Akansha',101,'Pune'],['Gopal',102,'Chennai'],['Suresh',103,'Madurai'],['Divya',104,'Dehradun'],['Nikhil',105,'Delhi']]


[['Akansha', 101, 'Pune'],
 ['Gopal', 102, 'Chennai'],
 ['Suresh', 103, 'Madurai'],
 ['Divya', 104, 'Dehradun'],
 ['Nikhil', 105, 'Delhi']]

In [141]:
s=pd.DataFrame(lst)

In [142]:
s

0    1         2
0  Akansha  101      Pune
1    Gopal  102   Chennai
2   Suresh  103   Madurai
3    Divya  104  Dehradun
4   Nikhil  105     Delhi

In [143]:
s.columns=['Name','ID','City']

In [144]:
s

Name   ID      City
0  Akansha  101      Pune
1    Gopal  102   Chennai
2   Suresh  103   Madurai
3    Divya  104  Dehradun
4   Nikhil  105     Delhi

In [150]:
a=pd.DataFrame(s,columns=['Name','ID','City','Company','E-Mail'])

In [152]:
a

Name   ID      City  Company  E-Mail
0  Akansha  101      Pune      NaN     NaN
1    Gopal  102   Chennai      NaN     NaN
2   Suresh  103   Madurai      NaN     NaN
3    Divya  104  Dehradun      NaN     NaN
4   Nikhil  105     Delhi      NaN     NaN

In [155]:
a.iloc[[0]]

Name   ID  City  Company  E-Mail
0  Akansha  101  Pune      NaN     NaN

In [160]:
a.loc[[0,1]]

Name   ID     City  Company  E-Mail
0  Akansha  101     Pune      NaN     NaN
1    Gopal  102  Chennai      NaN     NaN

In [161]:
a

Name   ID      City  Company  E-Mail
0  Akansha  101      Pune      NaN     NaN
1    Gopal  102   Chennai      NaN     NaN
2   Suresh  103   Madurai      NaN     NaN
3    Divya  104  Dehradun      NaN     NaN
4   Nikhil  105     Delhi      NaN     NaN

In [177]:
a.loc[4,'Name']

'Nikhil'

In [170]:
a.iloc[0,2]

'Pune'

In [171]:
a.iloc[3,0]

'Divya'

In [173]:
a.iloc[4,2]

'Delhi'

In [174]:
a.iloc[4,1]

105

In [178]:
a.iloc[1]

Name         Gopal
ID             102
City       Chennai
Company        NaN
E-Mail         NaN
Name: 1, dtype: object

In [179]:
a

Name   ID      City  Company  E-Mail
0  Akansha  101      Pune      NaN     NaN
1    Gopal  102   Chennai      NaN     NaN
2   Suresh  103   Madurai      NaN     NaN
3    Divya  104  Dehradun      NaN     NaN
4   Nikhil  105     Delhi      NaN     NaN

In [180]:
a.iloc[[1]]

Name   ID     City  Company  E-Mail
1  Gopal  102  Chennai      NaN     NaN

In [186]:
a.iloc[0:2,0:2]

Name   ID
0  Akansha  101
1    Gopal  102

In [187]:
a

Name   ID      City  Company  E-Mail
0  Akansha  101      Pune      NaN     NaN
1    Gopal  102   Chennai      NaN     NaN
2   Suresh  103   Madurai      NaN     NaN
3    Divya  104  Dehradun      NaN     NaN
4   Nikhil  105     Delhi      NaN     NaN

In [193]:
a.iloc[:2,:3]

Name   ID     City
0  Akansha  101     Pune
1    Gopal  102  Chennai

In [1]:
import pandas as pd
import numpy as np

In [5]:
np.random.seed()
s=np.random.randint(100,200,20)

In [6]:
s

array([110, 159, 137, 188, 141, 107, 100, 177, 187, 130, 193, 176, 177,
       123, 163, 123, 151, 145, 159, 175])

In [4]:
s.std()

30.548486050866742

In [12]:
np.random.seed()
s=np.random.randint(100,200,20).reshape(4,5)

In [13]:
s

array([[185, 142, 191, 133, 108],
       [101, 131, 162, 190, 155],
       [146, 165, 176, 184, 100],
       [177, 189, 196, 199, 163]])

In [24]:
print("I am learning how to code :D")


I am learning how to code :D


In [28]:
births_per_min = 300
births_per_hours=300*60
births_per_hours
birth_per_day=births_per_hours*24
birth_per_day



432000

In [2]:
a=a=True, 'Hello', 50, None, 'Mandeep'
print(a,type(a))

(True, 'Hello', 50, None, 'Mandeep') <class 'tuple'>


In [4]:
a='adarsh',
a,type(a)

(('adarsh',), tuple)

In [21]:
t=(True, None, 50, 'Hello', {1:100,2:200}, [4,5,6])
t[4][1]

100

In [29]:
t=(True, 'Hello', 5+5j, None, [10,20,30],{4,5,6})
t[1:6]

('Hello', (5+5j), None, [10, 20, 30], {4, 5, 6})

In [53]:
t[5]

{4, 5, 6}

In [47]:
for i in t:
    s=i[::-1]
    print(s)

TypeError: 'bool' object is not subscriptable

In [58]:
a=True, 'Hello', 50, None, 'Mandeep'
G,Greeting,Int_int,Aviable,Name=a


In [62]:
Int_int

50

In [63]:
a='adarsh','25','Arla'
name,age,vill=a

In [65]:
name,age,vill

('adarsh', '25', 'Arla')

In [70]:
t=()
for i in range(1,10):
    t+=i,
    print(i)
t

1
2
3
4
5
6
7
8
9


(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [71]:
t=[10,20,30,40]
t[0]==600
t

[10, 20, 30, 40]

In [89]:
t=(10,20,30,40,50,10,'adarsh')
t

(10, 20, 30, 40, 50, 10, 'adarsh')

In [93]:
t.index('adarsh')

6

In [100]:
d={1:100,2:200,3:300,4:400}
d

{1: 100, 2: 200, 3: 300, 4: 400}

In [96]:
d={1:100,2:200,3:300,4:400,1:"aa"}
d

{1: 'aa', 2: 200, 3: 300, 4: 400}

In [107]:
emp={'Name':'Kafeel','Age':26,'City':'Pune','Company':'TCS',1:220}
emp.keys(),emp.values()

(dict_keys(['Name', 'Age', 'City', 'Company', 1]),
 dict_values(['Kafeel', 26, 'Pune', 'TCS', 220]))

In [108]:
emp['Name']

'Kafeel'

In [109]:
emp['Age']

26

In [111]:
emp['Kafeel']

KeyError: 'Kafeel'

In [112]:
emp={'Name':'Kafeel','Age':26,'City':'Pune','Company':'TCS',1:220}
emp['Name']='Adarsh'

In [113]:
emp

{'Name': 'Adarsh', 'Age': 26, 'City': 'Pune', 'Company': 'TCS', 1: 220}

In [117]:
emp['Age']=30
emp,id(emp)

({'Name': 'Adarsh', 'Age': 30, 'City': 'Pune', 'Company': 'TCS', 1: 220},
 1805945341184)

In [116]:
emp,id(emp)

({'Name': 'Adarsh', 'Age': 30, 'City': 'Pune', 'Company': 'TCS', 1: 220},
 1805945341184)

In [121]:
a=('adarsh','kashyap'),('age',30)
b=dict(a)
b

{'adarsh': 'kashyap', 'age': 30}

In [125]:
a=tuple(enumerate('data'))

In [126]:
a

((0, 'd'), (1, 'a'), (2, 't'), (3, 'a'))

In [128]:
a=int(enumerate(1))

TypeError: 'int' object is not iterable

In [130]:
a=[10,20,None,"egg","adarsh"]
s=enumerate(a)
s

In [134]:
l1 = ["eat", "sleep", "repeat"]
list(enumerate(l1))

[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]

Return type: <class 'enumerate'>
[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
[(2, 'g'), (3, 'e'), (4, 'e'), (5, 'k')]


In [135]:
a='adarsh'
enumerate(a)

In [136]:
list(enumerate(a))

[(0, 'a'), (1, 'd'), (2, 'a'), (3, 'r'), (4, 's'), (5, 'h')]

In [141]:
a='egg','adarsh'
print(dict(list(enumerate(a))))

{0: 'egg', 1: 'adarsh'}


In [143]:
a=(10,20),(30,40)
dict(a)

{10: 20, 30: 40}

In [145]:
lis=10,20,'adarsh','kashyap','rahul'
list(enumerate(lis))

[(0, 10), (1, 20), (2, 'adarsh'), (3, 'kashyap'), (4, 'rahul')]

In [147]:
dict(enumerate(lis))

{0: 10, 1: 20, 2: 'adarsh', 3: 'kashyap', 4: 'rahul'}

In [149]:
list(enumerate(lis))

[(0, 10), (1, 20), (2, 'adarsh'), (3, 'kashyap'), (4, 'rahul')]

In [154]:
tuple(enumerate(lis))

((0, 10), (1, 20), (2, 'adarsh'), (3, 'kashyap'), (4, 'rahul'))

In [155]:
set(enumerate(lis))

{(0, 10), (1, 20), (2, 'adarsh'), (3, 'kashyap'), (4, 'rahul')}

In [159]:
a='adarsh'
dict(enumerate(a))

{0: 'a', 1: 'd', 2: 'a', 3: 'r', 4: 's', 5: 'h'}

In [160]:
a='adarsh'
set(enumerate(a))

{(0, 'a'), (1, 'd'), (2, 'a'), (3, 'r'), (4, 's'), (5, 'h')}

In [161]:
a='adarsh'
dict(enumerate(a))

{0: 'a', 1: 'd', 2: 'a', 3: 'r', 4: 's', 5: 'h'}

In [164]:
print(dir(str))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [165]:
dir(set)

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [167]:
a={'add','adarsh','kashyap'}
a.add('Rand')
a

{'Rand', 'adarsh', 'add', 'kashyap'}

In [176]:
a='shail is randua'
for i in range(1,20):
    print(a)
    print("he need sex")
    

shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex
shail is randua
he need sex


In [1]:
import pandas as pd

In [6]:
lst=[10,20,30,40,50,60,70,80]
s=pd.Series(lst)
print(type(pd.Series(lst)),pd.Series(lst))

<class 'pandas.core.series.Series'> 0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64


In [7]:
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [8]:
s.values

array([10, 20, 30, 40, 50, 60, 70, 80], dtype=int64)

In [10]:
s.shape

(8,)

In [12]:
s.index

RangeIndex(start=0, stop=8, step=1)

In [13]:
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [19]:
s.index=list('********')

In [20]:
s

*    10
*    20
*    30
*    40
*    50
*    60
*    70
*    80
dtype: int64

In [22]:
s.index

Index(['*', '*', '*', '*', '*', '*', '*', '*'], dtype='object')

In [23]:
emp_names=pd.Series(['Divya','Nikhil','Akansha','Gopal','Sunil','Saif Ali','Gyan','Vamsi','Ritesh','Sarwar','Mayank','Rudra','Shiva','Bandi'])

In [24]:
emp_names

0        Divya
1       Nikhil
2      Akansha
3        Gopal
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [30]:
for i in range(len(emp_names)):
    g='emp_'+str(i+1)
    print(g)
    

emp_1
emp_2
emp_3
emp_4
emp_5
emp_6
emp_7
emp_8
emp_9
emp_10
emp_11
emp_12
emp_13
emp_14


In [42]:
for i in range(len(emp_names)):
    g='emp_'+str(i+1)
    s=g
    print(s)
    
j=emp_names.index=[s]
print(j)

emp_1
emp_2
emp_3
emp_4
emp_5
emp_6
emp_7
emp_8
emp_9
emp_10
emp_11
emp_12
emp_13
emp_14


ValueError: Length mismatch: Expected axis has 14 elements, new values have 1 elements

In [35]:
import pandas as pd


In [43]:
emp_names=pd.Series(['Divya','Nikhil','Akansha','Gopal','Sunil','Saif Ali','Gyan','Vamsi','Ritesh','Sarwar','Mayank','Rudra','Shiva','Bandi'])

In [44]:
emp_names

0        Divya
1       Nikhil
2      Akansha
3        Gopal
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [47]:
emp_names.values,  emp_names.index,

ValueError: too many values to unpack (expected 3)

In [63]:
 emp_names.index=list('sdfghjkllkjshg')

In [64]:
emp_names.index

Index(['s', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'l', 'k', 'j', 's', 'h', 'g'], dtype='object')

In [68]:
emp_names.index=['emp_'+str(i+1) for i in range(len(emp_names))]

In [69]:
emp_names

emp_1        Divya
emp_2       Nikhil
emp_3      Akansha
emp_4        Gopal
emp_5        Sunil
emp_6     Saif Ali
emp_7         Gyan
emp_8        Vamsi
emp_9       Ritesh
emp_10      Sarwar
emp_11      Mayank
emp_12       Rudra
emp_13       Shiva
emp_14       Bandi
dtype: object

In [86]:
emp_names.index=      ["KASHYAP_"+'_'+str(i+1)   for i in range(len(emp_names))]

In [87]:
emp_names

KASHYAP__1        Divya
KASHYAP__2       Nikhil
KASHYAP__3      Akansha
KASHYAP__4        Gopal
KASHYAP__5        Sunil
KASHYAP__6     Saif Ali
KASHYAP__7         Gyan
KASHYAP__8        Vamsi
KASHYAP__9       Ritesh
KASHYAP__10      Sarwar
KASHYAP__11      Mayank
KASHYAP__12       Rudra
KASHYAP__13       Shiva
KASHYAP__14       Bandi
dtype: object

In [89]:
emp_names.values

array(['Divya', 'Nikhil', 'Akansha', 'Gopal', 'Sunil', 'Saif Ali', 'Gyan',
       'Vamsi', 'Ritesh', 'Sarwar', 'Mayank', 'Rudra', 'Shiva', 'Bandi'],
      dtype=object)

In [93]:
emp_names.name #='Adarsh'
emp_names

KASHYAP__1        Divya
KASHYAP__2       Nikhil
KASHYAP__3      Akansha
KASHYAP__4        Gopal
KASHYAP__5        Sunil
KASHYAP__6     Saif Ali
KASHYAP__7         Gyan
KASHYAP__8        Vamsi
KASHYAP__9       Ritesh
KASHYAP__10      Sarwar
KASHYAP__11      Mayank
KASHYAP__12       Rudra
KASHYAP__13       Shiva
KASHYAP__14       Bandi
Name: Adarsh, dtype: object

In [94]:
emp_names.name

'Adarsh'

In [96]:
emp_names

KASHYAP__1        Divya
KASHYAP__2       Nikhil
KASHYAP__3      Akansha
KASHYAP__4        Gopal
KASHYAP__5        Sunil
KASHYAP__6     Saif Ali
KASHYAP__7         Gyan
KASHYAP__8        Vamsi
KASHYAP__9       Ritesh
KASHYAP__10      Sarwar
KASHYAP__11      Mayank
KASHYAP__12       Rudra
KASHYAP__13       Shiva
KASHYAP__14       Bandi
Name: Adarsh, dtype: object

In [108]:
emp_names.index
for i in range(len(emp_names)):
    print(i)
for i in emp_names:
    print([i])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
['Divya']
['Nikhil']
['Akansha']
['Gopal']
['Sunil']
['Saif Ali']
['Gyan']
['Vamsi']
['Ritesh']
['Sarwar']
['Mayank']
['Rudra']
['Shiva']
['Bandi']


In [98]:
emp_names.iloc[0]

'Divya'

In [99]:
emp_names.iloc[1]

'Nikhil'

In [101]:
emp_names.iloc[13]

'Bandi'

In [109]:
emp_names

KASHYAP__1        Divya
KASHYAP__2       Nikhil
KASHYAP__3      Akansha
KASHYAP__4        Gopal
KASHYAP__5        Sunil
KASHYAP__6     Saif Ali
KASHYAP__7         Gyan
KASHYAP__8        Vamsi
KASHYAP__9       Ritesh
KASHYAP__10      Sarwar
KASHYAP__11      Mayank
KASHYAP__12       Rudra
KASHYAP__13       Shiva
KASHYAP__14       Bandi
Name: Adarsh, dtype: object

In [117]:
emp_names.index=  [ '20-'+ str(i+1)  for i in range(len(emp_names))]

In [118]:
emp_names

20-1        Divya
20-2       Nikhil
20-3      Akansha
20-4        Gopal
20-5        Sunil
20-6     Saif Ali
20-7         Gyan
20-8        Vamsi
20-9       Ritesh
20-10      Sarwar
20-11      Mayank
20-12       Rudra
20-13       Shiva
20-14       Bandi
Name: Adarsh, dtype: object

In [119]:
emp_names.iloc[::]

20-1        Divya
20-2       Nikhil
20-3      Akansha
20-4        Gopal
20-5        Sunil
20-6     Saif Ali
20-7         Gyan
20-8        Vamsi
20-9       Ritesh
20-10      Sarwar
20-11      Mayank
20-12       Rudra
20-13       Shiva
20-14       Bandi
Name: Adarsh, dtype: object

In [130]:
emp_names.iloc[5::-1]

20-6    Saif Ali
20-5       Sunil
20-4       Gopal
20-3     Akansha
20-2      Nikhil
20-1       Divya
Name: Adarsh, dtype: object

In [155]:
emp_names

'Rajeev'

In [138]:
emp_names.iloc[0]='Adarsh'

In [153]:
emp_names

'Rajeev'

In [148]:
emp_names=='Rajeev'

True

In [154]:
emp_names

'Rajeev'

In [156]:
emp_names=pd.Series(['Divya','Nikhil','Akansha','Gopal','Sunil','Saif Ali','Gyan','Vamsi','Ritesh','Sarwar','Mayank','Rudra','Shiva','Bandi'])

In [157]:
emp_names

0        Divya
1       Nikhil
2      Akansha
3        Gopal
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [158]:
emp_names

0        Divya
1       Nikhil
2      Akansha
3        Gopal
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [160]:
emp_names.index

RangeIndex(start=0, stop=14, step=1)

In [162]:
emp_names.values

array(['Divya', 'Nikhil', 'Akansha', 'Gopal', 'Sunil', 'Saif Ali', 'Gyan',
       'Vamsi', 'Ritesh', 'Sarwar', 'Mayank', 'Rudra', 'Shiva', 'Bandi'],
      dtype=object)

In [164]:
emp_names.iloc[2]

'Akansha'

In [166]:
emp_names.iloc[2]='Akans'

In [169]:
emp_names.iloc[3]='Gopi'

In [170]:
emp_names

0        Divya
1       Nikhil
2        Akans
3         Gopi
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [173]:
emp_names.iloc[4]='Suney'

In [179]:
emp_names[emp_names=="Rudra"]

11    Rudra
dtype: object

In [181]:
emp_names[emp_names=='Bandi']='Randi'

In [182]:
emp_names

0        Divya
1       Nikhil
2        Akans
3         Gopi
4        Suney
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Randi
dtype: object

In [1]:
import pandas as pd

In [2]:
emp_names=pd.Series(['Divya','Nikhil','Akansha','Gopal','Sunil','Saif Ali','Gyan','Vamsi','Ritesh','Sarwar','Mayank','Rudra','Shiva','Bandi'])

In [3]:
emp_names

0        Divya
1       Nikhil
2      Akansha
3        Gopal
4        Sunil
5     Saif Ali
6         Gyan
7        Vamsi
8       Ritesh
9       Sarwar
10      Mayank
11       Rudra
12       Shiva
13       Bandi
dtype: object

In [5]:
emp_names.index= "emp"+str(for i range(len(emp_names))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [2]:
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\Titanic.csv")

In [3]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [6]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [12]:
len(df)

891

In [15]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [17]:
df.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [22]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [28]:
df['Survived'].unique()

array([0, 1], dtype=int64)

In [29]:
df.Pclass.unique()

array([3, 1, 2], dtype=int64)

In [31]:
df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [36]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [42]:
df[['Survived','Sex']]

Survived     Sex
0           0    male
1           1  female
2           1  female
3           1  female
4           0    male
..        ...     ...
886         0    male
887         1  female
888         0  female
889         1    male
890         0    male

[891 rows x 2 columns]

In [60]:
177+687+2

866

In [56]:
 df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [58]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [49]:
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [61]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [62]:
df.shape

(891, 12)

In [63]:
df.dropna(inplace=True)

In [64]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [65]:
1,2,3,4,5

(1, 2, 3, 4, 5)

In [66]:
0==0

True

In [67]:
0==1

False

In [68]:
2+3j

(2+3j)

In [71]:
2+3j

(2+3j)

In [73]:
print(None )

None


In [76]:
None == 0

False

In [77]:
print('Hello, Shail')

Hello, Shail


In [78]:
a={10,10,20,30,40,50}
print(a)

{50, 20, 40, 10, 30}


In [80]:
number1 = 20
number2 = 30
s=number1+number2
print(s)

50


In [81]:
number1 = 40
number2 = 30
#Given two integer numbers, return their 
#product only if the product is equal to or lower than 1000. Otherwise, return their sum.

In [82]:
number1 = 40
number2 = 30
if number1*number2 <=1000:
    print(number1*number2 )
else:
    
    print( number1+number2 )

70


In [83]:
40*70

2800

In [95]:
previous_num = 0
for i in range(1,11):
    sum_u=previous_num+i
    s=sum_u
    print("privious number_",sum_u,"Current Number_",)

privious number_ 1 Current Number_
privious number_ 2 Current Number_
privious number_ 3 Current Number_
privious number_ 4 Current Number_
privious number_ 5 Current Number_
privious number_ 6 Current Number_
privious number_ 7 Current Number_
privious number_ 8 Current Number_
privious number_ 9 Current Number_
privious number_ 10 Current Number_


In [106]:
e=0
s=0
for i in range(1,11):
    e=e+i
    s+=i
    print("Current number_",s,"Previous Number_",i)

Current number_ 1 Previous Number_ 1
Current number_ 3 Previous Number_ 2
Current number_ 6 Previous Number_ 3
Current number_ 10 Previous Number_ 4
Current number_ 15 Previous Number_ 5
Current number_ 21 Previous Number_ 6
Current number_ 28 Previous Number_ 7
Current number_ 36 Previous Number_ 8
Current number_ 45 Previous Number_ 9
Current number_ 55 Previous Number_ 10


In [99]:
print("Printing current and previous number and their sum in a range(10)")
previous_num = 0
    
# loop from 1 to 10
for i in range(1, 11):
    x_sum = previous_num + i
    print("Current Number", i, "Previous Number ", previous_num, " Sum: ", x_sum)
    # modify previous number
    # set it to the current number
    previous_num = i

Printing current and previous number and their sum in a range(10)
Current Number 1 Previous Number  0  Sum:  1
Current Number 2 Previous Number  1  Sum:  3
Current Number 3 Previous Number  2  Sum:  5
Current Number 4 Previous Number  3  Sum:  7
Current Number 5 Previous Number  4  Sum:  9
Current Number 6 Previous Number  5  Sum:  11
Current Number 7 Previous Number  6  Sum:  13
Current Number 8 Previous Number  7  Sum:  15
Current Number 9 Previous Number  8  Sum:  17
Current Number 10 Previous Number  9  Sum:  19


In [110]:
str = "pynative"  #‘p’, ‘n’, ‘t’, ‘v’.
str[::2]

'pntv'

In [113]:
# accept input string from a user
word = input('Enter word ')
print("Original String:", word)

# get the length of a string
size = len(word)

# iterate a each character of a string
# start: 0 to start with first character
# stop: size-1 because index starts with 0
# step: 2 to get the characters present at even index like 0, 2, 4
print("Printing only even index chars")
for i in range(0, size - 1, 2):
    print("index[", i, "]", word[i])

Enter word "pynative"
Original String: "pynative"
Printing only even index chars
index[ 0 ] "
index[ 2 ] y
index[ 4 ] a
index[ 6 ] i
index[ 8 ] e


In [126]:
# accept input string from a user
word = input('Enter word ')
print("Original String:", word)

# get the length of a string
size = len(word)

# iterate a each character of a string
# start: 0 to start with first character
# stop: size-1 because index starts with 0
# step: 2 to get the characters present at even index like 0, 2, 4
print("Printing only even index chars")
for i in range(0, size , 2):
    print("index[", i, "]", word[i])

Enter word "pynative"
Original String: "pynative"
Printing only even index chars
index[ 0 ] "
index[ 2 ] y
index[ 4 ] a
index[ 6 ] i
index[ 8 ] e


In [143]:
str_i = "pynative"
size=len(str_i)
for i in range(0,size,2):
    print(i,str_i)
    
    

0 pynative
2 pynative
4 pynative
6 pynative


In [138]:
size

8

In [144]:
word="pynative"
for i in word[::2]:
    print(i)

p
n
t
v


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv(r"C:\Users\Lenovo\Downloads\emp.csv")

In [6]:
df

Name        Designation  Code       City  Depart_No
0  Akanksha     Data Scientist   101      Noida         10
1    Dinesh            Analyst   101     Mumbai         10
2      Gyan      Data Engineer   103      Delhi         20
3    Sakina          Developer   104       Pune         30
4    Puneet  Marketing Analyst   105  Bangalore         10
5   Haritha         Councellor   106    Chennai         20
6    Mahesh    Project Manager   107   Gurugram         50
7   Akshata   Business Analyst   108  Bangalore         30

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Name         8 non-null      object
 1   Designation  8 non-null      object
 2   Code         8 non-null      int64 
 3   City         8 non-null      object
 4   Depart_No    8 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 452.0+ bytes


In [8]:
df.describe()

Code  Depart_No
count    8.000000   8.000000
mean   104.375000  22.500000
std      2.615203  13.887301
min    101.000000  10.000000
25%    102.500000  10.000000
50%    104.500000  20.000000
75%    106.250000  30.000000
max    108.000000  50.000000

In [10]:
df.rename({'Name':'Emp_Name','Designation':'Degs','Code':'ID_Emp'},inplace=True)

In [11]:
df

Name        Designation  Code       City  Depart_No
0  Akanksha     Data Scientist   101      Noida         10
1    Dinesh            Analyst   101     Mumbai         10
2      Gyan      Data Engineer   103      Delhi         20
3    Sakina          Developer   104       Pune         30
4    Puneet  Marketing Analyst   105  Bangalore         10
5   Haritha         Councellor   106    Chennai         20
6    Mahesh    Project Manager   107   Gurugram         50
7   Akshata   Business Analyst   108  Bangalore         30

In [12]:
for i in df:
    print(i)

Name
Designation
Code
City
Depart_No


In [25]:
for i in df:
    
    
    print(df[i])
    print('*'*45)

0    Akanksha
1      Dinesh
2        Gyan
3      Sakina
4      Puneet
5     Haritha
6      Mahesh
7     Akshata
Name: Name, dtype: object
*********************************************
0       Data Scientist
1              Analyst
2        Data Engineer
3            Developer
4    Marketing Analyst
5           Councellor
6      Project Manager
7     Business Analyst
Name: Designation, dtype: object
*********************************************
0    101
1    101
2    103
3    104
4    105
5    106
6    107
7    108
Name: Code, dtype: int64
*********************************************
0        Noida
1       Mumbai
2        Delhi
3         Pune
4    Bangalore
5      Chennai
6     Gurugram
7    Bangalore
Name: City, dtype: object
*********************************************
0    10
1    10
2    20
3    30
4    10
5    20
6    50
7    30
Name: Depart_No, dtype: int64
*********************************************


In [26]:
d1={1:100,2:200}
len(d1)

2

In [31]:
emp={'Name':'Kafeel','Age':26,'City':'Pune','Company':'TCS'}
emp['Name'],emp['Age'], emp['City']

('Kafeel', 26, 'Pune')

In [32]:
emp['Salary']=25000

In [33]:
emp['Degsi']='Senior DA'

In [35]:
print(emp)

{'Name': 'Kafeel', 'Age': 26, 'City': 'Pune', 'Company': 'TCS', 'Salary': 25000, 'Degsi': 'Senior DA'}


In [36]:
emp['Name']='Adarsh'

In [38]:
print(emp)

{'Name': 'Adarsh', 'Age': 26, 'City': 'Pune', 'Company': 'TCS', 'Salary': 25000, 'Degsi': 'Senior DA'}


In [43]:
Month={"January":31,
       "February":28,
       "March":31,"April":30,"May":31,"June":30,"July":31,"August":31,"September":30,"October":31,"November":30, "December":31}
print(Month)

{'January': 31, 'February': 28, 'March': 31, 'April': 30, 'May': 31, 'June': 30, 'July': 31, 'August': 31, 'September': 30, 'October': 31, 'November': 30, 'December': 31}


In [44]:
Month['shail']=1995

In [45]:
Month

{'January': 31,
 'February': 28,
 'March': 31,
 'April': 30,
 'May': 31,
 'June': 30,
 'July': 31,
 'August': 31,
 'September': 30,
 'October': 31,
 'November': 30,
 'December': 31,
 'shail': 1995}

In [46]:
dic={}
dic['Name']='Adarsh'
dic['Age']=25
dic['Salary']=25000
dic['Desigination']='Assisatnt Professor'

In [48]:
print(dic)

{'Name': 'Adarsh', 'Age': 25, 'Salary': 25000, 'Desigination': 'Assisatnt Professor'}


In [51]:
dict([(10,20),('Name','Adarsh'),('Village','Arla')])

{10: 20, 'Name': 'Adarsh', 'Village': 'Arla'}